name: Run caesb-scraping.py

on:
  schedule:
    - cron: "0 * * * *"
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 
      
      - name: Install requirements.txt
        run: |
          pip3 install -r requirements.txt
      
      - name: Execute caesb-scraping.py
        run: |
          python3 caesb-scraping.py
        env:
          ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
          CONSUMER_SECRETKEY: ${{secrets.CONSUMER_SECRETKEY}}
          CONSUMER_APIKEY: ${{secrets.CONSUMER_APIKEY}}
          BEARER_TOKEN: ${{secrets.BEARER_TOKEN}}
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          LINK_DB: ${{secrets.LINK_DB}}
